<a href="https://colab.research.google.com/github/LizethArista/Manejo_de_datos/blob/main/2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy

NumPy es una biblioteca fundamental para manejo de datos en Python

Nos permite trabajar con arreglos numéricos de forma más eficiente que las listas normales


- Arreglos de una y varias dimensiones
- Formas y tipos de datos
- Indexación y rebanado
- Operaciones vectorizadas
- Filtros booleanos
- Broadcast
- Estadísticas básicas

In [ ]:
import numpy as np

print("Versión de NumPy:", np.__version__)

Versión de NumPy: 2.1.3


## ¿Por qué usar NumPy?

Las listas de Python son útiles, pero para operaciones numéricas grandes no son tan eficientes


Una lista es una estructura de datos flexible de Python, mientras que un arreglo de NumPy está pensado para hacer operaciones numéricas eficientes


NumPy ofrece:

- Arreglos homogéneos
- Operaciones vectorizadas
- Menos ciclos `for`
- Herramientas para álgebra y estadística


| Característica | Lista de Python | Arreglo NumPy |
|---|---|---|
| Tipo de datos | Puede mezclar tipos: enteros, textos, booleanos, etc. | Normalmente todos los elementos son del mismo tipo |
| Eficiencia | Menos eficiente para cálculos grandes | Más eficiente para operaciones numéricas |
| Operaciones | Se usan ciclos o comprensiones | Permite operaciones vectorizadas |
| Dimensiones | Normalmente se maneja como 1D, aunque puede anidarse | Puede ser 1D, 2D, 3D, etc. |
| Funciones matemáticas | No tiene funciones matemáticas integradas | Tiene muchas: suma, promedio, máximo, etc. |
| Uso principal | Estructura de datos general | Cálculo numérico y manejo de datos |

In [ ]:
lista = [1, 2, 3, 4]
arreglo = np.array(lista)

print("Lista:", lista)
print("Arreglo:", arreglo)

print("Tipo de lista:", type(lista))
print("Tipo de arreglo:", type(arreglo))

print("dtype:", arreglo.dtype)
print("shape:", arreglo.shape)

Lista: [1, 2, 3, 4]
Arreglo: [1 2 3 4]
Tipo de lista: <class 'list'>
Tipo de arreglo: <class 'numpy.ndarray'>
dtype: int64
shape: (4,)


In [ ]:
print(lista * 2)
print(arreglo * 2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


## Creación de arreglos

NumPy tiene varias funciones para crear arreglos:

| Función | Descripción |
|---|---|
| `np.array()` | Crea un arreglo desde una lista |
| `np.zeros()` | Crea arreglo lleno de ceros |
| `np.ones()` | Crea arreglo lleno de unos |
| `np.arange()` | Crea secuencias con paso |
| `np.linspace()` | Crea valores igualmente espaciados |
| `np.random.default_rng()` | Generador aleatorio |

In [ ]:
rng = np.random.default_rng(49)

a = np.array([10, 20, 30])
print("a:", a)



a: [10 20 30]


In [ ]:
b = np.zeros((2, 3), dtype=int)  # crea una matriz de 2 filas y 3 columnas
print("b:\n", b)

b:
 [[0 0 0]
 [0 0 0]]


In [ ]:
c = np.ones(5)
print("c:", c)

c: [1. 1. 1. 1. 1.]


In [ ]:
d = np.arange(1, 11, 2)  #genera números de 1 a 10 con paso 2
print("d:", d)


d: [1 3 5 7 9]


In [ ]:
e = np.linspace(0, 1, 5)
print("e:", e)

e: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
f = rng.integers(1, 101, size=6) # genera 6 enteros aleatorios entre 1 y 100
print("f:", f)

f: [30 57 46  7 20 18]


## Atributos de un arreglo

Los arreglos tienen propiedades importantes:

- `shape`: forma o dimensiones
- `ndim`: número de dimensiones
- `size`: cantidad total de elementos
- `dtype`: tipo de dato

In [ ]:
matriz = np.arange(1, 13).reshape(3, 4)

print(matriz)

print("ndim:", matriz.ndim)
print("shape:", matriz.shape)
print("size:", matriz.size)
print("dtype:", matriz.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64


## Cambiar forma con `reshape`

Podemos reorganizar los elementos de un arreglo sin cambiar sus datos.

In [ ]:
numeros = np.arange(1, 13)

print("Original:", numeros)

matriz_3x4 = numeros.reshape(3, 4)
print("Matriz 3x4:\n", matriz_3x4)

matriz_4x3 = numeros.reshape(4, 3)
print("Matriz 4x3:\n", matriz_4x3)

print("Aplanado:", matriz_3x4.flatten())

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Aplanado: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## Indexación y rebanado

Podemos acceder a elementos usando índices.

En arreglos de una dimensión:

```python
arreglo[posicion]
arreglo[inicio:fin:paso]


```
en una matriz
```python
matriz[fila, columna]

In [ ]:
numeros = np.arange(10, 110, 10)

print(numeros)

print("Primero:", numeros[0])
print("Último:", numeros[-1])
print("Rebanada 2:6:", numeros[2:6])
print("Cada 3 posiciones:", numeros[::3])

[ 10  20  30  40  50  60  70  80  90 100]
Primero: 10
Último: 100
Rebanada 2:6: [30 40 50 60]
Cada 3 posiciones: [ 10  40  70 100]


In [ ]:
notas = np.array([
    [8, 7, 9],
    [10, 6, 8],
    [5, 9, 10]
])

print(notas)
print("Fila 0, columna 0:", notas[0, 0])



[[ 8  7  9]
 [10  6  8]
 [ 5  9 10]]
Fila 0, columna 0: 8


In [ ]:
print(notas)
print("Fila completa 1:", notas[1])

[[ 8  7  9]
 [10  6  8]
 [ 5  9 10]]
Fila completa 1: [10  6  8]


In [ ]:
print(notas)
print("Columna 2 completa:", notas[:, 2])

[[ 8  7  9]
 [10  6  8]
 [ 5  9 10]]
Columna 2 completa: [ 9  8 10]


In [ ]:
print(notas)
print("Submatriz filas 0-1, columnas 1-2:\n", notas[0:2, 1:3])

[[ 8  7  9]
 [10  6  8]
 [ 5  9 10]]
Submatriz filas 0-1, columnas 1-2:
 [[7 9]
 [6 8]]


## Filtros booleanos

Los filtros booleanos permiten seleccionar elementos que cumplen una condición.

Ejemplo:

```python
arreglo[arreglo > 5]

In [ ]:
calificaciones = np.array([5, 7, 8, 10, 4, 9])

aprobo = calificaciones >= 7

print("Calificaciones:", calificaciones)
print("¿Aprobó?:", aprobo)
print("Aprobadas:", calificaciones[aprobo])
print("Pares:", calificaciones[calificaciones % 2 == 0])


Calificaciones: [ 5  7  8 10  4  9]
¿Aprobó?: [False  True  True  True False  True]
Aprobadas: [ 7  8 10  9]
Pares: [ 8 10  4]




## Operaciones vectorizadas

Con NumPy podemos hacer operaciones elemento por elemento sin escribir ciclos

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a ** 2:", a ** 2)
print("sqrt(a):", np.sqrt(a))

a + b: [11 22 33]
a - b: [ -9 -18 -27]
a * b: [10 40 90]
a / b: [0.1 0.1 0.1]
a ** 2: [1 4 9]
sqrt(a): [1.         1.41421356 1.73205081]


## Broadcasting

Broadcasting permite combinar arreglos de diferentes formas cuando las dimensiones son compatibles

Por ejemplo, sumar un número a toda una matriz

In [ ]:
m = np.arange(6).reshape(2, 3)

print("Matriz:\n", m)

print("Sumar 100:\n", m + 100)  # m + 100: suma 100 a todos los elementos

print("Sumar fila:\n", m + np.array([10, 20, 30])) #suma una fila compatible

print("Sumar columna:\n", m + np.array([[100], [200]])) #suma valores por columna

Matriz:
 [[0 1 2]
 [3 4 5]]
Sumar 100:
 [[100 101 102]
 [103 104 105]]
Sumar fila:
 [[10 21 32]
 [13 24 35]]
Sumar columna:
 [[100 101 102]
 [203 204 205]]


## Estadísticas y agregaciones

NumPy incluye funciones para calcular:

- Suma.
- Promedio.
- Máximo.
- Mínimo.
- Índice del máximo.
- Índice del mínimo.

In [ ]:
ventas = rng.integers(100, 500, size=(4, 5))

print("Ventas:\n", ventas)

print("Suma total:", ventas.sum())
print("Promedio:", ventas.mean())
print("Máximo:", ventas.max())
print("Mínimo:", ventas.min())
print("Índice del máximo:", ventas.argmax())

Ventas:
 [[307 349 460 362 338]
 [105 291 410 222 498]
 [103 303 164 144 201]
 [457 123 350 115 248]]
Suma total: 5550
Promedio: 277.5
Máximo: 498
Mínimo: 103
Índice del máximo: 9


## Uso de `axis`

Cuando trabajamos con matrices:

- `axis=0`: opera por columnas.
- `axis=1`: opera por filas.

Si `ventas` tiene forma `(4, 5)`:

- 4 filas pueden ser tiendas.
- 5 columnas pueden ser días.

In [ ]:
print("Ventas:\n", ventas)

print("Total por día:", ventas.sum(axis=0))
print("Total por tienda:", ventas.sum(axis=1))

print("Promedio por día:", ventas.mean(axis=0))
print("Promedio por tienda:", ventas.mean(axis=1))

Ventas:
 [[307 349 460 362 338]
 [105 291 410 222 498]
 [103 303 164 144 201]
 [457 123 350 115 248]]
Total por día: [ 972 1066 1384  843 1285]
Total por tienda: [1816 1526  915 1293]
Promedio por día: [243.   266.5  346.   210.75 321.25]
Promedio por tienda: [363.2 305.2 183.  258.6]


## Unir arreglos

Podemos combinar arreglos usando:

- `np.hstack()`: unir horizontalmente
- `np.vstack()`: unir verticalmente

In [ ]:
turno1 = np.array([8, 9, 7])
turno2 = np.array([10, 6, 9])

print("Horizontal:", np.hstack([turno1, turno2]))
print("Vertical:\n", np.vstack([turno1, turno2]))

Horizontal: [ 8  9  7 10  6  9]
Vertical:
 [[ 8  9  7]
 [10  6  9]]


Supongamos que tenemos calificaciones de tres estudiantes en tres materias

Queremos:

- Calcular promedio por estudiante
- Saber quién tiene el mejor promedio
- Contar cuántas materias aprobó cada estudiante

In [ ]:
alumnos = ["Ana", "Beto", "Carla"]
materias = ["Matemáticas", "Física", "Química"]

calificaciones = np.array([
    [8, 7, 9],
    [6, 8, 7],
    [10, 10, 9]
])

print("Calificaciones:\n", calificaciones)

promedios = calificaciones.mean(axis=1)

print("Promedios:", promedios)



Calificaciones:
 [[ 8  7  9]
 [ 6  8  7]
 [10 10  9]]
Promedios: [8.         7.         9.66666667]


In [ ]:
mejor_indice = np.argmax(promedios)

print("Mejor promedio:", alumnos[mejor_indice])
print("Promedio:", promedios[mejor_indice])


Mejor promedio: Carla
Promedio: 9.666666666666666


In [ ]:
aprobadas = calificaciones >= 7

print("Materias aprobadas por estudiante:\n", aprobadas)
print("Cantidad de materias aprobadas:", aprobadas.sum(axis=1))

Materias aprobadas por estudiante:
 [[ True  True  True]
 [False  True  True]
 [ True  True  True]]
Cantidad de materias aprobadas: [3 2 3]


## Ejercicio

1. Crea un arreglo con los números del 1 al 20
2. Filtra los números pares
3. Convierte ese arreglo en una matriz de 4 filas y 5 columnas
4. Calcula suma, promedio y máximo de la matriz
5. Crea una matriz de 3x3 con enteros aleatorios entre 1 y 10
6. Súmale 5 a todos los elementos